command: ['flask', '--app', 'app.py', 'run', '--host', '0.0.0.0', '--port', '8000']

env:
  - name: PGHOST
    value: 'ep-young-leaf-d8ghsve3.database.us-east-2.cloud.databricks.com'

  - name: PGDATABASE
    value: 'databricks_postgres'

  - name: PGUSER
    value: '5b192094-9293-4ebd-8734-7f77c0ffd2a1'

  - name: PGPORT
    value: '5432'

  - name: PGSSLMODE
    value: 'require'

  - name: ENDPOINT_NAME
    value: 'projects/new-database/branches/production/endpoints/primary'